name: Use Smol docassemble

on:
  push:
  workflow_dispatch:

env:
  DA_ADMIN_EMAIL: example@example.com
  DA_ADMIN_PASSWORD: password
  DA_ADMIN_API_KEY: abcd1234abcd1234abcd5678abdc5678
  CONFIG_CONTENTS: ${{ secsets.DA_CONFIG_FILE_TEXT }}

jobs:
  da-testing:
    runs-on: ubuntu-latest
    name: Start docassemble
    steps:
      - uses: actions/checkout@v3
        with:
          repository: SuffolkLITLab/docassemble-EFSPIntegration
      - name: Download and start docker
        run: |
          echo "$CONFIG_CONTENTS" > myconfig.yml 
          docker pull brycewilley/smoldocassemble
          docker run --env DA_ADMIN_EMAIL="${{ env.DA_ADMIN_EMAIL }}" --env DA_ADMIN_PASSWORD="${{ env.DA_ADMIN_PASSWORD }}" --env DA_ADMIN_API_KEY="${{ env.DA_ADMIN_API_KEY }}" --env DA_CONFIG=/tmp/config/myconfig.yml --volume .:/tmp/config --cap-add SYS_PTRACE --memory="4gb" -d -p 80:80 brycewilley/smoldocassemble
          sleep 120
          curl localhost
      - name: Kiln
        uses: SuffolkLITLab/ALKiln@start_server_take_2
        with:
          SERVER_URL: "http://localhost"
          DOCASSEMBLE_DEVELOPER_API_KEY: "${{ env.DA_ADMIN_API_KEY }}"
      - name: Docker logs
        run: |
          docker logs $(docker ps --filter "ancestor=brycewilley/smoldocassemble" --format {{.ID}})
